"""advanced/: the advanced configurations, as Compose overlays on top of compose.yaml.

No Docker needed, except where a test says so (it is skipped without it). What is checked:

- every link in a README of advanced/ points at a file that exists, and the files each README lists exist;
- the proxy files keep what a proxy must do for Headscale (the upgrade, no buffering, an HTTP/1.1 upstream);
- the Authentik blueprint accepts the console's redirect URIs and has nothing the console would call, and every
  reference in it resolves;
- the redirect URIs the documents give are the ones the code uses;
- the image's configuration rendered from each option's variables has the expected OIDC / route lines;
- every overlay merges with compose.yaml (alone and in combination) and the values that must agree do.

    python3 -m unittest tests.test_advanced
"""
import json
import os
import re
import shutil
import subprocess
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "aio"))
import render  # noqa: E402

ADVANCED = os.path.join(ROOT, "advanced")
HAVE_DOCKER = shutil.which("docker") is not None and subprocess.run(
    ["docker", "compose", "version"], capture_output=True).returncode == 0
# What the overlays require (:?) and ship empty in .env.example: a value for the checks only
CHECK_ENV = {"HSE_PUBLIC_URL": "https://vpn.example.test", "HSE_DOMAIN": "vpn.example.test", "ID_DOMAIN": "id.example.test",
             "HSE_TRUSTED_PROXIES": "192.0.2.10/32", "HEADSCALE_PG_HOST": "db.example.test", "HEADSCALE_PG_PASS": "x",
             "HEADSCALE_PG_RO_PASS": "y", "AUTHENTIK_SECRET_KEY": "x", "AUTHENTIK_PG_PASS": "x",
             "OIDC_CLIENT_SECRET": "x", "POCKET_ID_ENCRYPTION_KEY": "x"}


def read(*parts):
    with open(os.path.join(ROOT, *parts), encoding="utf-8") as fh:
        return fh.read()


def overlays():
    """advanced/*.yaml and advanced/oidc/*.yaml, relative to the root (not the Authentik blueprint)."""
    out = []
    for base in (ADVANCED, os.path.join(ADVANCED, "oidc")):
        out += [os.path.relpath(os.path.join(base, n), ROOT) for n in sorted(os.listdir(base)) if n.endswith(".yaml")]
    return out


def markdown_files():
    out = []
    for dirpath, _dirs, names in os.walk(ADVANCED):
        out += [os.path.join(dirpath, n) for n in names if n.endswith(".md")]
    return sorted(out)


def render_for(env):
    """The image's three outputs for an environment, as the supervisor would render them."""
    settings = render.load_settings(env, "/nonexistent/settings.json")
    v = render.to_vars(settings)
    return (v, render.render_caddyfile(v, "/data"), render.render_headscale_config(v),
            render.console_env(settings, "/data"))


class Layout(unittest.TestCase):
    def test_every_relative_link_exists(self):
        self.assertGreaterEqual(len(markdown_files()), 5)
        for md in markdown_files():
            for target in re.findall(r"\]\(([^)\s]+)\)", read(md)):
                if re.match(r"^[a-z]+:|^#", target):
                    continue
                path = os.path.normpath(os.path.join(os.path.dirname(md), target.split("#")[0]))
                self.assertTrue(os.path.exists(path), "%s links to %s, which does not exist" % (os.path.relpath(md, ROOT), target))

    def test_the_overlays_are_the_ones_the_index_lists(self):
        index = read("advanced", "README.md")
        for rel in overlays():
            self.assertIn(rel, index, "%s is not in advanced/README.md" % rel)

    def test_every_overlay_says_how_to_use_it(self):
        for rel in overlays():
            self.assertIn("docker compose -f compose.yaml -f %s" % rel, read(rel), rel)

    def test_the_old_directories_are_gone(self):
        for gone in ("deploy", "authentik"):
            self.assertFalse(os.path.exists(os.path.join(ROOT, gone)), gone)


class ProxyFiles(unittest.TestCase):
    def files(self):
        return {n: read("advanced", "proxy", n) for n in
                ("nginx.conf", "traefik-dynamic.yml", "Caddyfile", "nginx-proxy-manager.md")}

    def test_no_leftover_template_placeholders(self):
        for name, text in self.files().items():
            self.assertNotRegex(text, r"\$\{[A-Z_]+\}", name)
            self.assertNotIn("Generated by", text, name)

    def test_every_file_uses_the_same_placeholders(self):
        for name, text in self.files().items():
            if name != "nginx-proxy-manager.md":
                self.assertIn("AIO_HOST", text, name)
                self.assertIn("vpn.example.com", text, name)

    def test_nginx_keeps_what_headscale_needs(self):
        text = self.files()["nginx.conf"]
        self.assertIn("proxy_http_version 1.1;", text)
        self.assertIn("proxy_set_header Upgrade    $http_upgrade;", text)
        self.assertIn("proxy_set_header Connection $connection_upgrade;", text)
        self.assertIn("proxy_buffering    off;", text)
        self.assertIn("proxy_read_timeout  3600s;", text)
        self.assertIn("client_max_body_size 0;", text)
        self.assertIn("X-Forwarded-For   $proxy_add_x_forwarded_for", text)
        # nginx refuses a variable that a later map defines: the map is active and comes first
        self.assertRegex(text, r"(?m)^map \$http_upgrade \$connection_upgrade \{")
        self.assertLess(text.index("map $http_upgrade"), text.index("upstream headscale_stack"))
        self.assertLess(text.index("map $http_upgrade"), text.index("server {"))

    def test_traefik_and_caddy_stream_the_long_poll(self):
        files = self.files()
        self.assertIn('flushInterval: "-1"', files["traefik-dynamic.yml"])
        self.assertIn("flush_interval -1", files["Caddyfile"])
        self.assertIn("http://AIO_HOST:8080", files["traefik-dynamic.yml"])
        self.assertIn("reverse_proxy AIO_HOST:8080", files["Caddyfile"])

    def test_every_variant_says_how_to_configure_the_image(self):
        for name, text in self.files().items():
            if name == "nginx-proxy-manager.md":
                continue
            self.assertIn("HSE_TLS=off", text, name)
            self.assertRegex(text, r"HSE_TRUSTED_PROXIES=<[^>]+>/32", name)
            self.assertIn("3478", text, name)  # the DERP port does not go through the proxy

    def test_nothing_recommends_trusting_a_network(self):
        for path in markdown_files() + [os.path.join(ROOT, "advanced", "proxy.md")]:
            for m in re.finditer(r"HSE_TRUSTED_PROXIES=(\S+)", read(os.path.relpath(path, ROOT))):
                value = m.group(1)
                if value.startswith("<") or value.startswith("$"):
                    continue
                self.assertTrue(value.endswith("/32"), "%s recommends %s" % (path, value))

    def test_the_proxy_values_render_to_what_the_guide_claims(self):
        v, caddy, config, console = render_for({
            "HSE_PUBLIC_URL": "https://vpn.example.com", "HSE_TLS": "off", "HSE_HTTP_PORT": "8080",
            "HSE_TRUSTED_PROXIES": "192.168.1.50/32"})
        self.assertEqual(v["SSL_MODE"], "front")
        self.assertIn("trusted_proxies static 192.168.1.50/32", caddy)
        self.assertIn("trusted_proxies_strict", caddy)
        self.assertIn("header_up X-Real-IP {client_ip}", caddy)
        self.assertIn("header_up X-Forwarded-Proto https", caddy)
        self.assertIn("# HSTS: sent by the front proxy", caddy)
        self.assertIn("  - 192.168.1.50/32", config)


class Blueprint(unittest.TestCase):
    PATH = ("advanced", "oidc", "authentik", "blueprints", "headscale.yaml")

    def test_the_headscale_provider_accepts_headscales_and_the_consoles_addresses(self):
        text = read(*self.PATH)
        block = text[text.index("    id: provider\n"):text.index("    id: app\n")]
        self.assertIn("name: headscale", block)
        self.assertIn('url: !Format ["%s/oidc/callback", !Context public_url]', block)
        self.assertIn('url: !Format ["%s/admin/callback", !Context public_url]', block)
        self.assertIn('url: !Format ["%s/admin/", !Context public_url]', block)
        self.assertEqual(block.count("redirect_uri_type: authorization"), 2)
        self.assertEqual(block.count("redirect_uri_type: logout"), 1)

    def test_the_issuer_path_is_kept(self):
        self.assertIn("# Issuer = <public_url>/authentik/application/o/headscale/", read(*self.PATH))

    def test_nothing_the_console_called_is_left(self):
        text = read(*self.PATH)
        for gone in ("headscale-easy-web", "PORTAL_AUTHENTIK_TOKEN", "MFA_REQUIRED", "headscale-easy-invitation",
                     "headscale-easy-recovery", "headscale-easy-add-user", "headscale-easy-sign-out", "SMTP_HOST",
                     "PORTAL_OIDC"):
            self.assertNotIn(gone, text, gone)

    def test_every_reference_resolves(self):
        text = read(*self.PATH)
        ids = set(re.findall(r"(?m)^\s+id: (\S+)", text))
        self.assertEqual(sorted(set(re.findall(r"!KeyOf (\S+)", text)) - ids), [])
        defined = set(re.findall(r"(?m)^  (\w+): !Env", text))
        self.assertEqual(sorted(set(re.findall(r"!Context (\w+)", text)) - defined), [])


class RedirectUris(unittest.TestCase):
    def test_the_consoles_callback_is_what_the_code_uses(self):
        app = read("web", "app.py")
        self.assertIn('REDIRECT_URI = f"{PUBLIC_URL}{BASE}/callback"', app)
        self.assertRegex(read("web", "ui.py"), r'(?m)^BASE = "/admin"')

    def test_the_documents_give_exactly_those_two_addresses(self):
        wanted = {"/admin/callback", "/oidc/callback"}
        for doc in (("advanced", "oidc", "README.md"), ("docs", "advanced", "oidc.md"), ("docs", "advanced", "oidc.es.md")):
            text = read(*doc)
            found = set(re.findall(r"https?://[^\s`'\"|]*?(/(?:admin|oidc)/callback)", text))
            self.assertEqual(found, wanted, "/".join(doc))
            self.assertNotIn("/admin/oidc/callback", text, "/".join(doc))


class RenderedConfigurations(unittest.TestCase):
    def test_authentik_option(self):
        env = {"HSE_PUBLIC_URL": "https://vpn.example.com", "HSE_TLS": "auto", "ACME_EMAIL": "admin@example.com",
               "OIDC_ISSUER": "https://vpn.example.com/authentik/application/o/headscale/", "OIDC_CLIENT_ID": "headscale",
               "OIDC_CLIENT_SECRET": "secret", "HSE_AUTHENTIK_UPSTREAM": "authentik-server:9000"}
        v, caddy, config, console = render_for(env)
        self.assertEqual(v["AUTH_PROVIDER"], "authentik")
        self.assertIn("handle /authentik/* {\n        reverse_proxy authentik-server:9000 {", caddy)
        self.assertNotIn("/add-user", caddy)
        self.assertIn('issuer: "https://vpn.example.com/authentik/application/o/headscale/"', config)
        self.assertIn("email_verified_required: false", config)
        for name in ("AUTHENTIK_URL", "AUTHENTIK_API_TOKEN"):  # the console never calls Authentik's API
            self.assertNotIn(name, console)
        self.assertEqual(console["OIDC_ISSUER"], console["HEADSCALE_OIDC_ISSUER"])  # the console finds users by it

    def test_the_issuer_is_kept_byte_for_byte(self):
        issuer = "https://vpn.example.com/authentik/application/o/headscale/"
        _v, _caddy, config, console = render_for({
            "HSE_PUBLIC_URL": "https://vpn.example.com", "HSE_TLS": "off", "OIDC_ISSUER": issuer,
            "OIDC_CLIENT_ID": "headscale", "OIDC_CLIENT_SECRET": "s", "HSE_AUTHENTIK_UPSTREAM": "authentik-server:9000"})
        self.assertIn('issuer: "%s"' % issuer, config)  # not rewritten, not stripped of its trailing slash
        self.assertEqual(console["OIDC_ISSUER"], issuer)

    def test_pocket_id_option(self):
        env = {"HSE_PUBLIC_URL": "https://vpn.example.com", "HSE_TLS": "off", "HSE_TRUSTED_PROXIES": "172.30.0.10/32",
               "OIDC_ISSUER": "https://id.example.com", "OIDC_CLIENT_ID": "i" * 3, "OIDC_CLIENT_SECRET": "s" * 3,
               "PORTAL_ADMIN_EMAILS": "admin@example.com"}
        v, caddy, config, console = render_for(env)
        self.assertEqual(v["SSL_MODE"], "front")
        self.assertEqual(v["AUTH_PROVIDER"], "external")
        self.assertIn("trusted_proxies static 172.30.0.10/32", caddy)
        self.assertNotIn("handle /authentik/*", caddy)
        self.assertIn("email_verified_required: true", config)
        self.assertEqual(console["PORTAL_ADMIN_EMAILS"], "admin@example.com")

    def test_keycloak_and_google_variables_render(self):
        for issuer in ("https://sso.example.com/realms/hse", "https://accounts.google.com"):
            env = {"OIDC_ISSUER": issuer, "OIDC_CLIENT_ID": "headscale", "OIDC_CLIENT_SECRET": "s",
                   "PORTAL_ADMIN_EMAILS": "you@example.com", "HSE_PUBLIC_URL": "https://vpn.example.com", "HSE_TLS": "off"}
            v, caddy, config, console = render_for(env)
            self.assertEqual(v["AUTH_PROVIDER"], "external", issuer)
            self.assertIn('issuer: "%s"' % issuer, config)
            self.assertNotIn("handle /authentik/*", caddy)
            self.assertEqual(console["OIDC_ISSUER"], issuer)

    def test_the_documents_use_the_variables_the_image_reads(self):
        known = {name for name, _default in render.SETTINGS.values()}
        known |= {"HSE_ADMIN_PASSWORD", "HSE_HTTP_PORT", "HSE_HTTPS_PORT", "HSE_PROXY_BIND", "HSE_VERSION", "HSE_DOMAIN",
                  "HSE_SELF_IP", "ID_DOMAIN", "POSTGRES_VERSION", "POCKET_ID_ENCRYPTION_KEY", "ACME_EMAIL",
                  "HSE_REMOTE_CONFIG", "BACKUP_REMOTE", "BACKUP_REMOTE_KEEP_DAYS", "BACKUP_SYNC_INTERVAL",
                  "BACKUP_REMOTE_SSH_PORT", "BACKUP_AWS_ACCESS_KEY_ID", "BACKUP_AWS_SECRET_ACCESS_KEY",
                  "AUTHENTIK_SECRET_KEY", "AUTHENTIK_PG_PASS", "AUTHENTIK_ADMIN_EMAIL", "AUTHENTIK_BOOTSTRAP_PASSWORD",
                  "GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "TZ"}
        for rel in ("advanced/postgres.md", "advanced/proxy.md", "advanced/backup-remote.md", "advanced/oidc/README.md"):
            for name in re.findall(r"(?m)^#?([A-Z][A-Z0-9_]{3,})=", read(rel)):
                self.assertIn(name, known, "%s: %s is not a variable the image reads" % (rel, name))


@unittest.skipUnless(HAVE_DOCKER, "needs Docker Compose")
class ComposeOverlays(unittest.TestCase):
    def config(self, *files, extra=None):
        """`docker compose config` of compose.yaml plus the given overlays, as JSON."""
        args = ["docker", "compose", "-f", "compose.yaml"]
        for f in files:
            args += ["-f", f]
        res = subprocess.run(args + ["config", "--format", "json"], capture_output=True, text=True, cwd=ROOT,
                             env=dict(os.environ, **CHECK_ENV, **(extra or {})))
        self.assertEqual(res.returncode, 0, " ".join(files) + ": " + res.stderr[-400:])
        return json.loads(res.stdout)

    def test_every_overlay_merges(self):
        self.assertGreaterEqual(len(overlays()), 6)
        for rel in overlays():
            self.config(rel)

    def test_the_options_combine(self):
        for combo in (("advanced/proxy.yaml", "advanced/postgres.yaml"),
                      ("advanced/proxy.yaml", "advanced/postgres-bundled.yaml", "advanced/backup-remote.yaml"),
                      ("advanced/proxy.yaml", "advanced/oidc/authentik.yaml", "advanced/postgres.yaml", "advanced/backup-remote.yaml")):
            self.config(*combo)

    def test_none_mounts_the_docker_socket_or_runs_privileged(self):
        for rel in overlays():
            for name, svc in self.config(rel)["services"].items():
                self.assertFalse(svc.get("privileged"), "%s %s" % (rel, name))
                for vol in svc.get("volumes", []):
                    self.assertNotIn("docker.sock", str(vol.get("source", "")), "%s %s" % (rel, name))

    def test_the_simple_file_is_left_alone(self):
        cfg = self.config()
        self.assertEqual(sorted(cfg["services"]), ["headscale-easy"])

    def test_proxy_overlay(self):
        svc = self.config("advanced/proxy.yaml")["services"]["headscale-easy"]
        self.assertEqual(svc["environment"]["HSE_TLS"], "off")
        self.assertEqual(svc["environment"]["HSE_TRUSTED_PROXIES"], "192.0.2.10/32")
        ports = {(p["target"], p["protocol"]): p.get("host_ip") for p in svc["ports"]}
        self.assertEqual(ports[(80, "tcp")], "127.0.0.1")          # plain HTTP for the proxy only
        self.assertNotIn((443, "tcp"), ports)                       # the proxy owns 443
        self.assertIn((3478, "udp"), ports)                         # the relay is not HTTP: still published

    def test_proxy_overlay_requires_the_proxy_address(self):
        res = subprocess.run(["docker", "compose", "-f", "compose.yaml", "-f", "advanced/proxy.yaml", "config", "-q"],
                             capture_output=True, text=True, cwd=ROOT,
                             env={k: v for k, v in dict(os.environ, **CHECK_ENV).items() if k != "HSE_TRUSTED_PROXIES"})
        self.assertNotEqual(res.returncode, 0)
        self.assertIn("HSE_TRUSTED_PROXIES", res.stderr)

    def test_postgres_overlays(self):
        ext = self.config("advanced/postgres.yaml")
        env = ext["services"]["headscale-easy"]["environment"]
        self.assertEqual(sorted(ext["services"]), ["headscale-easy"])
        self.assertEqual(env["HEADSCALE_DB_TYPE"], "postgres")
        self.assertEqual(env["HEADSCALE_PG_SSLMODE"], "require")
        self.assertEqual(env["HEADSCALE_PG_RO_USER"], "headscale_ro")
        bundled = self.config("advanced/postgres-bundled.yaml")
        self.assertEqual(sorted(bundled["services"]), ["headscale-easy", "postgres"])
        app = bundled["services"]["headscale-easy"]
        self.assertEqual(app["environment"]["HEADSCALE_PG_HOST"], "postgres")
        self.assertEqual(app["depends_on"]["postgres"]["condition"], "service_healthy")  # Headscale needs the database
        self.assertEqual(app["cap_drop"], ["ALL"])
        # PostgreSQL 18's image keeps its data in a versioned folder below /var/lib/postgresql
        targets = [v["target"] for v in bundled["services"]["postgres"]["volumes"]]
        self.assertEqual(targets, ["/var/lib/postgresql"])

    def test_the_postgres_passwords_are_required_and_none_ships(self):
        for rel in ("advanced/postgres.yaml", "advanced/postgres-bundled.yaml"):
            res = subprocess.run(["docker", "compose", "-f", "compose.yaml", "-f", rel, "config", "-q"],
                                 capture_output=True, text=True, cwd=ROOT,
                                 env={k: v for k, v in dict(os.environ, **CHECK_ENV).items() if not k.startswith("HEADSCALE_PG_PASS")})
            self.assertNotEqual(res.returncode, 0, rel)
            self.assertIn("HEADSCALE_PG_PASS", res.stderr, rel)
        with open(os.path.join(ROOT, ".env.example"), encoding="utf-8") as fh:
            shipped = [line for line in fh if re.match(r"^HEADSCALE_PG_(RO_)?PASS=\S", line)]
        self.assertEqual(shipped, [])  # nobody starts with a default password

    def test_the_sql_the_docs_name_is_the_one_the_image_runs(self):
        for rel in ("docs/advanced/postgres.md", "docs/advanced/postgres.es.md", "advanced/postgres.md"):
            self.assertIn("templates/headscale-pg-readonly.sql", read(rel), rel)
        self.assertTrue(os.path.exists(os.path.join(ROOT, "templates", "headscale-pg-readonly.sql")))

    def test_authentik_overlay(self):
        cfg = self.config("advanced/oidc/authentik.yaml")
        aio = cfg["services"]["headscale-easy"]["environment"]
        self.assertEqual(aio["HSE_AUTHENTIK_UPSTREAM"], "authentik-server:9000")
        self.assertTrue(aio["OIDC_ISSUER"].endswith("/authentik/application/o/headscale/"))
        for name in ("AUTHENTIK_URL", "AUTHENTIK_API_TOKEN"):  # the console never calls Authentik's API
            self.assertNotIn(name, aio)
        for name in ("authentik-server", "authentik-worker"):
            self.assertEqual(cfg["services"][name]["environment"]["AUTHENTIK_WEB__PATH"], "/authentik/")
            sources = [v["source"] for v in cfg["services"][name]["volumes"]]
            self.assertTrue(any(s.endswith("/blueprints") and os.path.isdir(s) for s in sources), name)
        # the AIO must not wait for Authentik to be *healthy* (its first start outlasts the health check)
        dep = cfg["services"]["headscale-easy"]["depends_on"]["authentik-server"]
        self.assertEqual(dep["condition"], "service_started")
        # Authentik's own SMTP settings do not collide with the console's (SMTP_*)
        self.assertNotIn("SMTP_HOST", cfg["services"]["authentik-server"]["environment"])

    def test_pocket_id_overlay(self):
        cfg = self.config("advanced/oidc/pocket-id.yaml")
        aio = cfg["services"]["headscale-easy"]["environment"]
        proxy = cfg["services"]["proxy"]
        address = proxy["networks"]["default"]["ipv4_address"]
        self.assertEqual(aio["HSE_TRUSTED_PROXIES"], address + "/32")  # the proxy, and only the proxy
        self.assertEqual(aio["HSE_TLS"], "off")
        self.assertTrue(aio["HSE_PUBLIC_URL"].startswith("https://"))
        aliases = proxy["networks"]["default"]["aliases"]
        self.assertEqual(len(aliases), 2)  # both public names lead to the proxy inside the project
        pid = cfg["services"]["pocket-id"]["environment"]
        self.assertEqual(pid["APP_URL"], "https://id.example.test")
        self.assertEqual(pid["TRUST_PROXY"], "true")
        subnet = cfg["networks"]["default"]["ipam"]["config"][0]["subnet"]
        self.assertTrue(address.startswith(subnet.rsplit(".", 1)[0] + "."))
        self.assertFalse(cfg["services"]["pocket-id"].get("ports"))  # only through the proxy
        ports = {(p["target"], p["protocol"]) for p in cfg["services"]["headscale-easy"]["ports"]}
        self.assertEqual(ports, {(3478, "udp")})                      # the proxy owns 80 and 443

    def test_backup_remote_overlay(self):
        cfg = self.config("advanced/backup-remote.yaml")
        side = cfg["services"]["backup-remote"]
        self.assertEqual(side["environment"]["BACKUP_MODE"], "sync")
        self.assertEqual([v["read_only"] for v in side["volumes"] if v["target"] == "/backups"], [True])


if __name__ == "__main__":
    unittest.main()
