"""deploy/examples: the examples of the advanced edition (Block 4 of PHASE4_EXECUTION_PLAN.md).

No Docker needed, except where a test says so (it is skipped without it). What is checked:

- every link in a README points at a file that exists;
- the front-proxy files keep what a proxy must do for Headscale (the upgrade, no buffering, an HTTP/1.1 upstream)
  and no leftover envsubst placeholders from the 1.x templates;
- the Authentik blueprint is the 1.x one plus the console's redirect URIs, and nothing taken away;
- the redirect URIs the documents give are the ones the code uses;
- the all-in-one image's configuration rendered from each example's variables has the expected OIDC / route lines;
- every example compose file parses, and the values that have to agree with each other do.

    python3 -m unittest tests.test_examples
"""
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "aio"))
import render  # noqa: E402

EXAMPLES = os.path.join(ROOT, "deploy", "examples")
COMPOSE_DIR = os.path.join(ROOT, "deploy", "compose")
HAVE_DOCKER = shutil.which("docker") is not None and subprocess.run(
    ["docker", "compose", "version"], capture_output=True).returncode == 0


def read(*parts):
    with open(os.path.join(ROOT, *parts), encoding="utf-8") as fh:
        return fh.read()


def markdown_files():
    out = []
    for base in (EXAMPLES, COMPOSE_DIR):
        for dirpath, _dirs, names in os.walk(base):
            out += [os.path.join(dirpath, n) for n in names if n.endswith(".md")]
    return sorted(out)


def compose_files():
    out = []
    for dirpath, _dirs, names in os.walk(EXAMPLES):
        out += [os.path.join(dirpath, n) for n in names if n.startswith("docker-compose") and n.endswith(".yml")]
    return sorted(out)


def render_for(env):
    """The image's three outputs for an environment, as the supervisor would render them."""
    settings = render.load_settings(env, "/nonexistent/settings.json")
    v = render.to_vars(settings)
    return (v, render.render_caddyfile(v, "/data"), render.render_headscale_config(v),
            render.console_env(settings, "/data"))


def env_block(text, names):
    """KEY=value lines of the fenced blocks of a markdown file, for the given names; <placeholders> replaced."""
    out = {}
    for line in text.splitlines():
        m = re.match(r"^([A-Z_]+)=(.*?)(\s+#.*)?$", line.strip())
        if m and m.group(1) in names:
            out[m.group(1)] = re.sub(r"<[^>]+>", "x", m.group(2)).strip()
    return out


class Links(unittest.TestCase):
    def test_every_relative_link_exists(self):
        self.assertGreaterEqual(len(markdown_files()), 6)
        for md in markdown_files():
            for target in re.findall(r"\]\(([^)\s]+)\)", read(md)):
                if re.match(r"^[a-z]+:|^#", target):
                    continue
                path = os.path.normpath(os.path.join(os.path.dirname(md), target.split("#")[0]))
                self.assertTrue(os.path.exists(path), "%s links to %s, which does not exist" % (os.path.relpath(md, ROOT), target))

    def test_every_example_folder_has_a_readme(self):
        for name in sorted(os.listdir(EXAMPLES)):
            path = os.path.join(EXAMPLES, name)
            if os.path.isdir(path) and name != "postgresql":  # postgresql: block 5
                self.assertTrue(os.path.exists(os.path.join(path, "README.md")), name)

    def test_the_files_each_readme_lists_exist(self):
        for name in ("authentik", "pocket-id", "front-proxy"):
            text = read("deploy", "examples", name, "README.md")
            for ref in re.findall(r"\| \[`([^`]+)`\]\(", text):
                self.assertTrue(os.path.exists(os.path.join(EXAMPLES, name, ref)), "%s: %s" % (name, ref))


class FrontProxy(unittest.TestCase):
    def files(self):
        d = os.path.join(EXAMPLES, "front-proxy")
        return {n: read("deploy", "examples", "front-proxy", n) for n in
                ("nginx.conf", "traefik-dynamic.yml", "Caddyfile", "nginx-proxy-manager.md", "README.md")}

    def test_no_leftover_template_placeholders(self):
        for name, text in self.files().items():
            self.assertNotRegex(text, r"\$\{[A-Z_]+\}", name)
            self.assertNotIn("install.sh", text, name)
            self.assertNotIn("Generated by", text, name)
            self.assertNotIn("headscale-config.yaml", text, name)  # 1.x file: the image renders its own

    def test_every_file_uses_the_same_placeholders(self):
        for name, text in self.files().items():
            if name != "README.md":
                self.assertIn("AIO_HOST", text, name)
                self.assertIn("vpn.example.com", text, name)

    def test_nginx_keeps_what_headscale_needs(self):
        text = self.files()["nginx.conf"]
        self.assertIn("proxy_http_version 1.1;", text)
        self.assertIn("proxy_set_header Upgrade    $http_upgrade;", text)
        self.assertIn("proxy_set_header Connection $connection_upgrade;", text)
        self.assertIn("proxy_buffering    off;", text)
        self.assertIn("proxy_read_timeout  3600s;", text)
        self.assertIn("client_max_body_size 0;", text)
        self.assertIn("X-Forwarded-For   $proxy_add_x_forwarded_for", text)
        # nginx refuses a variable that a later map defines: the map is active and comes first
        self.assertRegex(text, r"(?m)^map \$http_upgrade \$connection_upgrade \{")
        self.assertLess(text.index("map $http_upgrade"), text.index("upstream headscale_stack"))
        self.assertLess(text.index("map $http_upgrade"), text.index("server {"))

    def test_traefik_and_caddy_stream_the_long_poll(self):
        files = self.files()
        self.assertIn('flushInterval: "-1"', files["traefik-dynamic.yml"])
        self.assertIn("flush_interval -1", files["Caddyfile"])
        self.assertIn("http://AIO_HOST:8080", files["traefik-dynamic.yml"])
        self.assertIn("reverse_proxy AIO_HOST:8080", files["Caddyfile"])

    def test_every_variant_says_how_to_configure_the_image(self):
        for name, text in self.files().items():
            if name in ("README.md", "nginx-proxy-manager.md"):
                continue
            self.assertIn("HSE_TLS=off", text, name)
            self.assertRegex(text, r"HSE_TRUSTED_PROXIES=<[^>]+>/32", name)
            self.assertIn("3478", text, name)  # the DERP port does not go through the proxy

    def test_the_readmes_never_recommend_trusting_a_network(self):
        for name in ("README.md", "nginx-proxy-manager.md"):
            text = self.files()[name]
            self.assertIn("/32", text)
            for m in re.finditer(r"HSE_TRUSTED_PROXIES=(\S+)", text):
                value = m.group(1)
                if value.startswith("<") or value.startswith("$"):
                    continue
                self.assertTrue(value.endswith("/32"), "%s recommends %s" % (name, value))

    def test_the_proxy_values_render_to_what_the_readme_claims(self):
        v, caddy, config, console = render_for({
            "HSE_PUBLIC_URL": "https://vpn.example.com", "HSE_TLS": "off", "HSE_HTTP_PORT": "8080",
            "HSE_TRUSTED_PROXIES": "192.168.1.50/32"})
        self.assertEqual(v["SSL_MODE"], "front")
        self.assertIn("trusted_proxies static 192.168.1.50/32", caddy)
        self.assertIn("trusted_proxies_strict", caddy)
        self.assertIn("header_up X-Real-IP {client_ip}", caddy)
        self.assertIn("header_up X-Forwarded-Proto https", caddy)
        self.assertIn("# HSTS: sent by the front proxy", caddy)
        self.assertIn("  - 192.168.1.50/32", config)


class Blueprint(unittest.TestCase):
    def test_it_is_the_1x_blueprint_plus_the_consoles_redirect_uris(self):
        old = read("authentik", "blueprints", "headscale.yaml").splitlines()
        new = read("deploy", "examples", "authentik", "blueprints", "headscale.yaml").splitlines()
        kept = set(new)
        removed = [l for l in old if l not in kept]
        self.assertEqual(removed, ["# Headscale Easy — Authentik blueprint"])  # only the title line was reworded
        added = [l for l in new if l not in set(old)]
        self.assertTrue(any("/admin/callback" in l for l in added))
        self.assertTrue(any("redirect_uri_type: logout" in l or "/admin/" in l for l in added))

    def test_the_headscale_provider_accepts_headscales_and_the_consoles_addresses(self):
        text = read("deploy", "examples", "authentik", "blueprints", "headscale.yaml")
        block = text[text.index("    id: provider\n"):text.index("    id: app\n")]
        self.assertIn("name: headscale", block)
        self.assertIn('url: !Format ["%s/oidc/callback", !Context public_url]', block)
        self.assertIn('url: !Format ["%s/admin/callback", !Context public_url]', block)
        self.assertIn('url: !Format ["%s/admin/", !Context public_url]', block)
        self.assertEqual(block.count("redirect_uri_type: authorization"), 2)
        self.assertEqual(block.count("redirect_uri_type: logout"), 1)

    def test_the_issuer_path_matches_the_1x_stack(self):
        text = read("deploy", "examples", "authentik", "blueprints", "headscale.yaml")
        self.assertIn("# Issuer = <public_url>/authentik/application/o/headscale/", text)

    def test_branding_is_a_copy(self):
        for name in os.listdir(os.path.join(ROOT, "authentik", "branding")):
            with open(os.path.join(ROOT, "authentik", "branding", name), "rb") as a, \
                    open(os.path.join(EXAMPLES, "authentik", "branding", name), "rb") as b:
                self.assertEqual(a.read(), b.read(), name)

    def test_the_original_is_untouched(self):
        # 1.x keeps using it until phase 6: it must still carry only the Headscale callback on that provider
        text = read("authentik", "blueprints", "headscale.yaml")
        block = text[text.index("    id: provider\n"):text.index("    id: app\n")]
        self.assertNotIn("/admin/callback", block)


class RedirectUris(unittest.TestCase):
    def test_the_consoles_callback_is_what_the_code_uses(self):
        app = read("web", "app.py")
        self.assertIn('REDIRECT_URI = f"{PUBLIC_URL}{BASE}/callback"', app)
        self.assertRegex(read("web", "ui.py"), r'(?m)^BASE = "/admin"')

    def test_the_documents_give_exactly_those_two_addresses(self):
        wanted = {"/admin/callback", "/oidc/callback"}
        for doc in (("authentik", "README.md"), ("pocket-id", "README.md"), ("keycloak.md",), ("google.md",)):
            text = read("deploy", "examples", *doc)
            found = set(re.findall(r"https?://[^\s`'\"|]*?(/(?:admin|oidc)/callback)", text))
            self.assertEqual(found, wanted, "/".join(doc))
            self.assertNotIn("/admin/oidc/callback", text, "/".join(doc))


class RenderedConfigurations(unittest.TestCase):
    def test_authentik_example(self):
        env = {"HSE_PUBLIC_URL": "https://vpn.example.com", "HSE_TLS": "auto", "ACME_EMAIL": "admin@example.com",
               "OIDC_ISSUER": "https://vpn.example.com/authentik/application/o/headscale/", "OIDC_CLIENT_ID": "headscale",
               "OIDC_CLIENT_SECRET": "secret", "HSE_AUTHENTIK_UPSTREAM": "authentik-server:9000",
               "AUTHENTIK_URL": "http://authentik-server:9000/authentik", "AUTHENTIK_API_TOKEN": "token"}
        v, caddy, config, console = render_for(env)
        self.assertEqual(v["AUTH_PROVIDER"], "authentik")
        self.assertIn("handle /authentik/* {\n        reverse_proxy authentik-server:9000 {", caddy)
        self.assertIn("redir /add-user /authentik/if/flow/headscale-easy-add-user/ 302", caddy)
        self.assertIn('issuer: "https://vpn.example.com/authentik/application/o/headscale/"', config)
        self.assertIn("email_verified_required: false", config)
        self.assertEqual(console["AUTHENTIK_URL"], "http://authentik-server:9000/authentik")
        self.assertEqual(console["AUTHENTIK_API_TOKEN"], "token")
        self.assertEqual(console["OIDC_ISSUER"], console["HEADSCALE_OIDC_ISSUER"])  # the console finds users by it

    def test_the_issuer_of_a_1x_stack_is_kept_byte_for_byte(self):
        issuer = "https://vpn.example.com/authentik/application/o/headscale/"
        _v, _caddy, config, console = render_for({
            "HSE_PUBLIC_URL": "https://vpn.example.com", "HSE_TLS": "off", "OIDC_ISSUER": issuer,
            "OIDC_CLIENT_ID": "headscale", "OIDC_CLIENT_SECRET": "s", "HSE_AUTHENTIK_UPSTREAM": "authentik-server:9000"})
        self.assertIn('issuer: "%s"' % issuer, config)  # not rewritten, not stripped of its trailing slash
        self.assertEqual(console["OIDC_ISSUER"], issuer)

    def test_pocket_id_example(self):
        env = {"HSE_PUBLIC_URL": "https://vpn.example.com", "HSE_TLS": "off", "HSE_TRUSTED_PROXIES": "172.30.0.10/32",
               "OIDC_ISSUER": "https://id.example.com", "OIDC_CLIENT_ID": "i" * 3, "OIDC_CLIENT_SECRET": "s" * 3,
               "PORTAL_ADMIN_EMAILS": "admin@example.com"}
        v, caddy, config, console = render_for(env)
        self.assertEqual(v["SSL_MODE"], "front")
        self.assertEqual(v["AUTH_PROVIDER"], "external")
        self.assertIn("trusted_proxies static 172.30.0.10/32", caddy)
        self.assertNotIn("handle /authentik/*", caddy)
        self.assertIn("email_verified_required: true", config)
        self.assertEqual(console["PORTAL_ADMIN_EMAILS"], "admin@example.com")

    def test_keycloak_and_google_blocks(self):
        names = ("OIDC_ISSUER", "OIDC_CLIENT_ID", "OIDC_CLIENT_SECRET", "PORTAL_ADMIN_EMAILS")
        for doc, issuer in (("keycloak.md", "https://sso.example.com/realms/hse"),
                            ("google.md", "https://accounts.google.com")):
            block = env_block(read("deploy", "examples", doc), names)
            self.assertEqual(block["OIDC_ISSUER"], issuer, doc)
            self.assertTrue(block["OIDC_CLIENT_ID"] and block["OIDC_CLIENT_SECRET"], doc)
            env = dict(block, HSE_PUBLIC_URL="https://vpn.example.com", HSE_TLS="off")
            v, caddy, config, console = render_for(env)
            self.assertEqual(v["AUTH_PROVIDER"], "external", doc)
            self.assertIn('issuer: "%s"' % issuer, config)
            self.assertNotIn("handle /authentik/*", caddy)
            self.assertEqual(console["OIDC_ISSUER"], issuer)

    def test_no_example_asks_for_a_setting_the_image_ignores(self):
        known = {name for name, _default in render.SETTINGS.values()}
        known |= {"HSE_ADMIN_PASSWORD", "HSE_HTTP_PORT", "HSE_HTTPS_PORT", "HSE_VERSION", "HSE_DOMAIN", "HSE_SELF_IP",
                  "ID_DOMAIN", "AUTHENTIK_API_TOKEN"}
        # what the image reads through load_settings, in the AIO service of every example compose file
        for path in compose_files():
            text = read(os.path.relpath(path, ROOT))
            section = text[text.index("  headscale-easy:\n"):]
            section = section[:section.index("\n  authentik-postgresql:")] if "authentik-postgresql:" in section else section
            for name in re.findall(r"(?m)^      ([A-Z][A-Z0-9_]+):", section.split("    ports:")[0]):
                self.assertIn(name, known | {"HSE_TLS", "TZ", "ACME_EMAIL"}, "%s: %s is not read by the image" % (path, name))


@unittest.skipUnless(HAVE_DOCKER, "needs Docker Compose")
class ComposeFiles(unittest.TestCase):
    def config(self, path, extra=None):
        """`docker compose config` of an example, with its .env.example as .env, as JSON."""
        src = os.path.dirname(path)
        with tempfile.TemporaryDirectory() as tmp:
            work = os.path.join(tmp, "x")
            shutil.copytree(src, work)
            if os.path.exists(os.path.join(work, ".env.example")):
                shutil.copy(os.path.join(work, ".env.example"), os.path.join(work, ".env"))
            res = subprocess.run(["docker", "compose", "-f", os.path.join(work, os.path.basename(path)), "--profile", "*",
                                  "config", "--format", "json"], capture_output=True, text=True,
                                 # the examples require their secrets and ship them empty: a value for the check only
                                 env=dict(os.environ, HEADSCALE_PG_PASS="check-only", HEADSCALE_PG_RO_PASS="check-only", **(extra or {})))
            self.assertEqual(res.returncode, 0, path + ": " + res.stderr[-400:])
            return json.loads(res.stdout)

    def test_every_example_compose_parses(self):
        self.assertGreaterEqual(len(compose_files()), 2)
        for path in compose_files():
            self.config(path)

    def test_none_mounts_the_docker_socket_or_runs_privileged(self):
        for path in compose_files():
            for name, svc in self.config(path)["services"].items():
                self.assertFalse(svc.get("privileged"), "%s %s" % (path, name))
                for vol in svc.get("volumes", []):
                    self.assertNotIn("docker.sock", str(vol.get("source", "")), "%s %s" % (path, name))

    def test_authentik_example(self):
        cfg = self.config(os.path.join(EXAMPLES, "authentik", "docker-compose.yml"))
        aio = cfg["services"]["headscale-easy"]["environment"]
        self.assertEqual(aio["HSE_AUTHENTIK_UPSTREAM"], "authentik-server:9000")
        self.assertTrue(aio["OIDC_ISSUER"].endswith("/authentik/application/o/headscale/"))
        self.assertIn("/authentik/application/o/headscale/", aio["OIDC_ISSUER"])
        self.assertEqual(aio["AUTHENTIK_URL"], "http://authentik-server:9000/authentik")
        for name in ("authentik-server", "authentik-worker"):
            self.assertEqual(cfg["services"][name]["environment"]["AUTHENTIK_WEB__PATH"], "/authentik/")
            sources = [v["source"] for v in cfg["services"][name]["volumes"]]
            self.assertTrue(any(s.endswith("/blueprints") for s in sources), name)
        # the console token and the one Authentik creates for its service account are the same variable
        self.assertEqual(cfg["services"]["authentik-server"]["environment"]["PORTAL_AUTHENTIK_TOKEN"], aio["AUTHENTIK_API_TOKEN"])
        # the AIO must not wait for Authentik to be *healthy* (its first start outlasts the health check)
        dep = cfg["services"]["headscale-easy"]["depends_on"]["authentik-server"]
        self.assertEqual(dep["condition"], "service_started")

    def test_pocket_id_example(self):
        cfg = self.config(os.path.join(EXAMPLES, "pocket-id", "docker-compose.yml"))
        aio = cfg["services"]["headscale-easy"]["environment"]
        proxy = cfg["services"]["proxy"]
        address = proxy["networks"]["default"]["ipv4_address"]
        self.assertEqual(aio["HSE_TRUSTED_PROXIES"], address + "/32")  # the proxy, and only the proxy
        self.assertEqual(aio["HSE_TLS"], "off")
        self.assertTrue(aio["HSE_PUBLIC_URL"].startswith("https://"))
        aliases = proxy["networks"]["default"]["aliases"]
        self.assertEqual(len(aliases), 2)  # both public names lead to the proxy inside the project
        self.assertEqual(cfg["services"]["pocket-id"]["environment"]["APP_URL"], "https://id.example.com")
        self.assertEqual(cfg["services"]["pocket-id"]["environment"]["TRUST_PROXY"], "true")
        subnet = cfg["networks"]["default"]["ipam"]["config"][0]["subnet"]
        self.assertTrue(address.startswith(subnet.rsplit(".", 1)[0] + "."))
        self.assertNotIn("ports", {k for k, v in cfg["services"]["pocket-id"].items() if v})  # only through the proxy


class PostgresqlExample(unittest.TestCase):
    DIR = os.path.join(EXAMPLES, "postgresql")

    def setUp(self):
        if not HAVE_DOCKER:
            self.skipTest("docker compose is not available")

    def test_services_and_the_start_order(self):
        cfg = ComposeFiles.config(self, os.path.join(self.DIR, "docker-compose.yml"))
        self.assertEqual(sorted(cfg["services"]), ["headscale-easy", "postgres"])
        app = cfg["services"]["headscale-easy"]
        self.assertEqual(app["environment"]["HEADSCALE_DB_TYPE"], "postgres")
        self.assertEqual(app["environment"]["HEADSCALE_PG_HOST"], "postgres")
        self.assertEqual(app["depends_on"]["postgres"]["condition"], "service_healthy")  # Headscale needs the database
        self.assertEqual(app["cap_drop"], ["ALL"])

    def test_the_read_only_role_is_in_the_env_and_no_password_ships(self):
        with open(os.path.join(self.DIR, ".env.example"), encoding="utf-8") as fh:
            env = dict(line.strip().split("=", 1) for line in fh if "=" in line and not line.lstrip().startswith("#"))
        self.assertEqual(env["HEADSCALE_PG_RO_USER"], "headscale_ro")
        self.assertEqual(env["HEADSCALE_PG_PASS"], "")       # nobody starts with a default password
        self.assertEqual(env["HEADSCALE_PG_RO_PASS"], "")

    def test_the_password_is_required(self):
        res = subprocess.run(["docker", "compose", "-f", os.path.join(self.DIR, "docker-compose.yml"), "config", "-q"],
                             capture_output=True, text=True, env={k: v for k, v in os.environ.items() if not k.startswith("HEADSCALE_PG")},
                             cwd=tempfile.mkdtemp())
        self.assertNotEqual(res.returncode, 0)
        self.assertIn("HEADSCALE_PG_PASS", res.stderr)

    def test_the_sql_is_the_one_the_image_runs(self):
        with open(os.path.join(self.DIR, "readonly-role.sql"), "rb") as a, \
                open(os.path.join(ROOT, "templates", "headscale-pg-readonly.sql"), "rb") as b:
            self.assertEqual(a.read(), b.read())


if __name__ == "__main__":
    unittest.main()
