"""First-run wizard of the all-in-one image (setup mode).

Started by the supervisor instead of the console while there is no
/data/config/settings.json and no HSE_PUBLIC_URL. Listens on 127.0.0.1:8000
behind the setup-mode Caddy (plain HTTP on :80) and answers only
/console/setup* and /console/static/*; everything else redirects to /console/setup.

    token -> language -> server URL + TLS -> admin account -> sign-up mode ->
    tailnet + isolation -> relays (DERP) -> backups -> finish

A one-time token (data/config/setup-token, also printed in the logs) gates
every step. The wizard creates the admin account (accounts.db) as it goes (two-factor
is optional; the console suggests it after sign-in); at the end it renders the config, briefly runs Headscale to create the
API key, the admin's Headscale user and the isolation policy, writes
settings.json (the marker that setup is done), deletes the token and exits 0.
The supervisor then switches to run mode. Every step is safe to repeat.

Standard library only; reuses web/ (UI, i18n, QR, local accounts).
"""
from __future__ import annotations

import hmac
import http.cookies
import json
import logging
import mimetypes
import os
import re
import secrets
import signal
import subprocess
import sys
import threading
import time
import urllib.parse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "aio"))
sys.path.insert(0, os.environ.get("HSE_WEB_DIR") or os.path.join(ROOT, "web"))

import local_accounts as lac  # noqa: E402
import render  # noqa: E402
from i18n import LANGUAGES, _, pick_lang, set_lang  # noqa: E402
from ui import BASE, message_page  # noqa: E402
from wizard_checks import (  # noqa: E402,F401
    EMAIL_RE, TAILNET_RE, TLS_MODES, USERNAME_RE, SetupError, check_backups, check_derp, check_email,
    check_network, check_server, check_signup, check_url, valid_text,
)
from wizard_pages import (  # noqa: E402,F401
    SETUP, STEPS, admin_page, backups_page, derp_page, done_page, finish_page, language_page, network_page,
    server_page, signup_page, token_page,
)

log = logging.getLogger("wizard")

STATIC_DIR = Path(os.environ.get("HSE_WEB_DIR") or os.path.join(ROOT, "web")) / "static"
# Served files, by URL path: a request never builds a filesystem path
STATIC_FILES = {f.relative_to(STATIC_DIR).as_posix(): f for f in STATIC_DIR.rglob("*") if f.is_file()}
HEADSCALE_BIN = os.environ.get("HSE_HEADSCALE_BIN", "headscale")
PORT = int(os.environ.get("HSE_WIZARD_PORT", "8000"))
HOST = os.environ.get("HSE_WIZARD_HOST", "127.0.0.1")
HEADSCALE_START_TIMEOUT = float(os.environ.get("HSE_START_TIMEOUT", "90"))
EXIT_DELAY = float(os.environ.get("HSE_WIZARD_EXIT_DELAY", "3"))
SESSION_TTL = 2 * 3600
MAX_BODY = 16 * 1024



# Headscale policy of NETWORK_ISOLATION=true
ISOLATION_POLICY = """{
  // Generated by Headscale Easy (NETWORK_ISOLATION=true).
  // Each user only reaches their own devices, admins included, and may use
  // exit nodes to reach the internet (without autogroup:internet an exit node
  // forwards nothing). Edit it in the web UI: Access controls.
  "acls": [
    {"action": "accept", "src": ["autogroup:member"], "dst": ["autogroup:self:*"]},
    {"action": "accept", "src": ["autogroup:member"], "dst": ["autogroup:internet:*"]}
  ]
}
"""


# -----------------------------------------------------------------------------
# Token, rate limit and sessions
# -----------------------------------------------------------------------------

def token_path(data_dir: str) -> str:
    return os.path.join(data_dir, "config", "setup-token")


def ensure_token(data_dir: str) -> str:
    """The one-time setup token: kept across wizard restarts, deleted when setup ends."""
    path = token_path(data_dir)
    try:
        with open(path, encoding="utf-8") as fh:
            token = fh.read().strip()
        if token:
            return token
    except OSError:
        pass
    token = secrets.token_urlsafe(24)
    render.write_file(path, token + "\n")
    return token


def read_token(data_dir: str) -> str:
    try:
        with open(token_path(data_dir), encoding="utf-8") as fh:
            return fh.read().strip()
    except OSError:
        return ""


def banner(token: str) -> str:
    bar = "=" * 64
    return "\n".join([
        bar,
        "  HEADSCALE EASY: FIRST-RUN SETUP",
        "",
        "  Open  http://<this-host>/console/setup  in a browser and enter",
        "  this one-time token:",
        "",
        "      " + token,
        "",
        "  (also in /data/config/setup-token; it is deleted when setup ends)",
        bar,
    ])


class RateLimit:
    """At most ``limit`` failures in ``window`` seconds, for every client together
    (the wizard sits behind Caddy, so the client address is not reliable)."""

    def __init__(self, limit=5, window=60.0, clock=time.monotonic):
        self.limit, self.window, self.clock = limit, window, clock
        self.fails: list[float] = []
        self.lock = threading.Lock()

    def wait(self) -> int:
        """Seconds to wait before another attempt (0 = allowed)."""
        with self.lock:
            now = self.clock()
            self.fails = [t for t in self.fails if now - t < self.window]
            return int(self.window - (now - self.fails[0])) + 1 if len(self.fails) >= self.limit else 0

    def fail(self):
        with self.lock:
            self.fails.append(self.clock())


class Sessions:
    def __init__(self, clock=time.time):
        self.clock = clock
        self.items: dict[str, dict] = {}
        self.lock = threading.Lock()

    def new(self) -> tuple[str, dict]:
        with self.lock:
            now = self.clock()
            self.items = {k: v for k, v in self.items.items() if v["exp"] > now}
            if len(self.items) >= 50:  # drop the oldest
                self.items.pop(min(self.items, key=lambda k: self.items[k]["exp"]))
            sid = secrets.token_urlsafe(24)
            self.items[sid] = {"exp": now + SESSION_TTL, "csrf": secrets.token_urlsafe(24), "authed": False,
                               "data": {}}
            return sid, self.items[sid]

    def get(self, sid: str | None) -> dict | None:
        with self.lock:
            sess = self.items.get(sid or "")
            if sess and sess["exp"] > self.clock():
                return sess
            self.items.pop(sid or "", None)
            return None


# -----------------------------------------------------------------------------
# Finish: render, Headscale API key + user + policy, settings.json
# -----------------------------------------------------------------------------

def _hs_env() -> dict:
    return {k: os.environ[k] for k in ("PATH", "HOME", "LANG", "TZ", "SSL_CERT_FILE") if k in os.environ}


def _hs(paths: dict, *args, timeout=30, stdin=None) -> tuple[int | None, str]:
    argv = [HEADSCALE_BIN, *args, "-c", paths["config"]]
    try:
        res = subprocess.run(argv, input=stdin, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True,
                             timeout=timeout, env=_hs_env(), stdin=None if stdin is not None else subprocess.DEVNULL)
    except subprocess.TimeoutExpired:
        return None, "timed out"
    except OSError as exc:
        return None, str(exc)
    return res.returncode, _strip(res.stdout)


def _strip(text: str) -> str:
    return re.sub(r"\x1b\[[0-9;]*[A-Za-z]", "", text or "").strip()


class Finisher:
    """Applies the collected settings. Idempotent: a retry never duplicates the
    API key, the Headscale user or the policy, and settings.json is written last."""

    def __init__(self, data_dir: str, env=None):
        self.data_dir = data_dir
        self.env = os.environ if env is None else env
        self.paths = render.paths(data_dir)

    def run(self, stored: dict, username: str):
        pending = self.paths["settings"] + ".pending"
        secret = ""
        try:
            with open(self.paths["settings"], encoding="utf-8") as fh:
                secret = json.load(fh).get("session_secret", "")
        except (OSError, ValueError, AttributeError):
            pass
        stored = dict(stored, session_secret=secret or secrets.token_urlsafe(48))
        render.write_file(pending, json.dumps(stored, indent=2, sort_keys=True) + "\n")
        try:
            settings = render.load_settings(self.env, pending)
            render.render_all(settings, self.data_dir)
        except ValueError as exc:
            raise SetupError(_("Invalid settings: {detail}", detail=str(exc))) from exc

        self.configure_headscale(settings, username)

        os.replace(pending, self.paths["settings"])
        os.chmod(self.paths["settings"], 0o600)
        try:
            os.unlink(token_path(self.data_dir))
        except OSError:
            pass

    def configure_headscale(self, settings: dict, username: str):
        """Run Headscale just long enough to create the API key, the admin's user and the policy."""
        os.makedirs(self.paths["hs_dir"], mode=0o700, exist_ok=True)
        proc = subprocess.Popen([HEADSCALE_BIN, "serve", "-c", self.paths["config"]], stdin=subprocess.DEVNULL,
                                stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, env=_hs_env())
        try:
            self.wait_healthy(proc)
            self.ensure_api_key()
            self.ensure_user(username)
            if settings.get("network_isolation", "true") == "true":
                self.ensure_policy()
        finally:
            proc.terminate()
            try:
                proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()
                proc.wait()

    def wait_healthy(self, proc):
        deadline = time.monotonic() + HEADSCALE_START_TIMEOUT
        while time.monotonic() < deadline:
            if proc.poll() is not None:
                err = _strip((proc.stderr.read() or b"").decode(errors="replace"))[-600:]
                raise SetupError(_("Headscale stopped on start: {detail}", detail=err or proc.returncode))
            code, _out = _hs(self.paths, "health", timeout=5)
            if code == 0:
                return
            time.sleep(1)
        raise SetupError(_("Headscale did not become healthy in time."))

    def ensure_api_key(self):
        try:
            with open(self.paths["api_key"], encoding="utf-8") as fh:
                if fh.read().strip():
                    return
        except OSError:
            pass
        code, out = _hs(self.paths, "apikeys", "create", "--expiration", "90d")
        key = out.splitlines()[-1].strip() if out else ""
        if code != 0 or not key:
            raise SetupError(_("Could not create the Headscale API key: {detail}", detail=out or code))
        render.write_file(self.paths["api_key"], key + "\n")

    def ensure_user(self, username: str):
        code, out = _hs(self.paths, "users", "list", "-o", "json")
        names = set()
        if code == 0:
            try:
                names = {u.get("name") for u in json.loads(out) or []}
            except (ValueError, AttributeError):
                names = set()
        if username in names:
            return
        code, out = _hs(self.paths, "users", "create", username)
        if code != 0:
            raise SetupError(_("Could not create the Headscale user: {detail}", detail=out or code))

    def ensure_policy(self):
        code, _out = _hs(self.paths, "policy", "get")
        if code == 0:  # one exists: keep it
            return
        code, out = _hs(self.paths, "policy", "set", "-f", "/dev/stdin", stdin=ISOLATION_POLICY)
        if code != 0:
            raise SetupError(_("Could not apply the isolation policy: {detail}", detail=out or code))




# -----------------------------------------------------------------------------
# HTTP
# -----------------------------------------------------------------------------

class Wizard:
    def __init__(self, data_dir: str, env=None, exit_callback=None):
        self.data_dir = data_dir
        self.env = os.environ if env is None else env
        self.sessions = Sessions()
        self.limit = RateLimit()
        self.finisher = Finisher(data_dir, self.env)
        self.exit_callback = exit_callback or (lambda: None)
        self.finish_lock = threading.Lock()
        self.finished = False

    def next_step(self, data: dict) -> str:
        """First step that is not done yet."""
        for step, key in (("language", "lang"), ("server", "server"), ("admin", "admin"),
                          ("signup", "signup"), ("network", "network"), ("derp", "derp"), ("backups", "backups")):
            if not data.get(key):
                return step
        return "finish"


class Handler(BaseHTTPRequestHandler):
    server_version = "headscale-easy"
    sys_version = ""
    wizard: Wizard  # set on the server

    def log_message(self, fmt, *args):
        log.info("%s", fmt % args)

    # --- responses ---
    def send(self, status: int, body: str | bytes, ctype="text/html; charset=utf-8", headers=None):
        data = body.encode() if isinstance(body, str) else body
        self.send_response(status)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(data)))
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("Referrer-Policy", "same-origin")
        if ctype.startswith("text/html"):
            self.send_header("Cache-Control", "no-store")
            self.send_header("Content-Security-Policy",
                             "default-src 'self'; img-src 'self' data:; frame-ancestors 'none'; form-action 'self'")
        for k, v in headers or []:
            self.send_header(k, v)
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(data)

    def redirect(self, location: str, headers=None, status=303):
        self.send_response(status)
        self.send_header("Location", location)
        self.send_header("Content-Length", "0")
        for k, v in headers or []:
            self.send_header(k, v)
        self.end_headers()

    def forbidden(self, text=None):
        self.send(403, message_page(_("No permission"), text or _("Enter the setup token first.")))

    def cookie(self, name: str) -> str | None:
        jar = http.cookies.SimpleCookie(self.headers.get("Cookie", ""))
        return jar[name].value if name in jar else None

    @staticmethod
    def set_cookie(name: str, value: str, max_age: int, path: str = SETUP) -> tuple[str, str]:
        return ("Set-Cookie", f"{name}={value}; Path={path}; HttpOnly; SameSite=Strict; Max-Age={max_age}")

    # --- routing ---
    def do_HEAD(self):
        self.do_GET()

    def do_GET(self):
        self.route("GET")

    def do_POST(self):
        self.route("POST")

    def route(self, method: str):
        set_lang(pick_lang(self.cookie("hse_lang"), self.headers.get("Accept-Language")))
        path = urlparse(self.path).path.rstrip("/") or "/"
        try:
            if path.startswith(BASE + "/static/") and method == "GET":
                return self.static(path[len(BASE + "/static/"):])
            if path == SETUP or path.startswith(SETUP + "/"):
                return self.setup_step(method, path[len(SETUP):].strip("/"))
            return self.redirect(SETUP, status=302)
        except Exception:  # noqa: BLE001
            log.exception("request failed")
            return self.send(500, message_page(_("Something went wrong"), _("See the container logs for details.")))

    def static(self, name: str):
        target = STATIC_FILES.get(name)
        if target is None:
            return self.send(404, "Not found", "text/plain")
        ctype = "font/woff2" if target.suffix == ".woff2" else (mimetypes.guess_type(target.name)[0]
                                                                or "application/octet-stream")
        self.send(200, target.read_bytes(), ctype, [("Cache-Control", "public, max-age=31536000, immutable")])

    def form(self) -> dict:
        try:
            length = int(self.headers.get("Content-Length", "0"))
        except ValueError:
            length = 0
        raw = self.rfile.read(min(max(length, 0), MAX_BODY)).decode("utf-8", errors="replace")
        return {k: v[0] for k, v in urllib.parse.parse_qs(raw, keep_blank_values=True).items()}

    def setup_step(self, method: str, step: str):
        wiz = self.wizard
        sess = wiz.sessions.get(self.cookie("hse_setup"))
        headers = []
        if sess is None:
            if step:  # every step needs the token first
                return self.forbidden()
            sid, sess = wiz.sessions.new()
            headers.append(self.set_cookie("hse_setup", sid, SESSION_TTL))
        form = self.form() if method == "POST" else {}
        if method == "POST" and not hmac.compare_digest(str(form.get("csrf", "")), sess["csrf"]):
            return self.send(403, message_page(_("No permission"), _("Invalid or expired form. Reload the page.")))

        if not step:
            if method == "GET" and not sess["authed"]:
                return self.send(200, token_page(sess), headers=headers)
            if method == "GET":
                return self.redirect(f"{SETUP}/{wiz.next_step(sess['data'])}")
            return self.check_token(sess, form, headers)

        if not sess["authed"] or step not in STEPS:
            return self.forbidden() if not sess["authed"] else self.send(404, "Not found", "text/plain")
        data = sess["data"]
        nxt = wiz.next_step(data)
        if STEPS.index(step) > STEPS.index(nxt):
            return self.redirect(f"{SETUP}/{nxt}")  # a step is missing before this one
        return getattr(self, "step_" + step)(method, sess, form, headers)

    def check_token(self, sess: dict, form: dict, headers: list):
        wiz = self.wizard
        wait = wiz.limit.wait()
        if wait:
            return self.send(429, message_page(_("Too many attempts"), _("Wait a minute and try again.")),
                             headers=[("Retry-After", str(wait))])
        expected = read_token(wiz.data_dir)
        given = str(form.get("token", "")).strip()
        if not expected or not hmac.compare_digest(given.encode(), expected.encode()):
            wiz.limit.fail()
            log.warning("wrong setup token")
            return self.send(403, token_page(sess, _("That token is not valid.")), headers=headers)
        sess["authed"] = True
        return self.redirect(f"{SETUP}/language", headers)

    # --- steps ---
    def step_language(self, method, sess, form, headers):
        data = sess["data"]
        if method == "GET":
            return self.send(200, language_page(sess, data.get("lang") or pick_lang(
                self.cookie("hse_lang"), self.headers.get("Accept-Language"))))
        lang = str(form.get("lang", ""))
        if lang not in LANGUAGES:
            return self.send(400, language_page(sess, "en"))
        data["lang"] = lang
        return self.redirect(f"{SETUP}/server", [self.set_cookie("hse_lang", lang, 31536000, BASE)])

    def step_server(self, method, sess, form, headers):
        data = sess["data"]
        if method == "GET":
            return self.send(200, server_page(sess, data.get("server", {})))
        try:
            data["server"] = check_server(form.get("public_url", ""), form.get("tls", ""), form.get("acme_email", ""))
        except SetupError as exc:
            return self.send(400, server_page(sess, {k: form.get(k, "") for k in ("public_url", "tls", "acme_email")},
                                              str(exc)))
        return self.redirect(f"{SETUP}/admin")

    def step_admin(self, method, sess, form, headers):
        data = sess["data"]
        if method == "GET":
            return self.send(200, admin_page(sess, data.get("admin") or {
                "email": self.wizard.env.get("HSE_ADMIN_EMAIL", "")}))
        values = {"email": form.get("email", ""), "username": form.get("username", "")}
        try:
            email = check_email(values["email"])
            username = values["username"].strip()
            if not USERNAME_RE.match(username):
                raise SetupError(_("3-32 characters: letters, numbers, - and _"))
            if form.get("password") != form.get("password2"):
                raise SetupError(_("The passwords do not match."))
            account_id = create_admin(email, username, form.get("password", ""))
        except (SetupError, ValueError) as exc:
            return self.send(400, admin_page(sess, values, str(exc)))
        data["admin"] = {"email": email, "username": username, "account_id": account_id}
        return self.redirect(f"{SETUP}/signup")

    def step_signup(self, method, sess, form, headers):
        data = sess["data"]
        if method == "GET":
            return self.send(200, signup_page(sess, data.get("signup", {})))
        try:
            data["signup"] = check_signup(form.get("mode", ""), form.get("first_key") == "1")
        except SetupError as exc:
            return self.send(400, signup_page(sess, {"signup_mode": form.get("mode", ""),
                                                     "first_key": form.get("first_key") == "1"}, str(exc)))
        return self.redirect(f"{SETUP}/network")

    def step_network(self, method, sess, form, headers):
        data = sess["data"]
        if method == "GET":
            return self.send(200, network_page(sess, data.get("network", {})))
        try:
            data["network"] = check_network(form.get("tailnet_name", ""), form.get("isolation") == "1",
                                            form.get("base_domain", ""), data.get("server", {}).get("public_url", ""))
        except SetupError as exc:
            return self.send(400, network_page(sess, {"tailnet_name": form.get("tailnet_name", ""),
                                                      "base_domain": form.get("base_domain", ""),
                                                      "network_isolation": "true" if form.get("isolation") else "false"},
                                               str(exc)))
        return self.redirect(f"{SETUP}/derp")

    def step_derp(self, method, sess, form, headers):
        data = sess["data"]
        if method == "GET":
            return self.send(200, derp_page(sess, data.get("derp", {})))
        try:
            data["derp"] = check_derp(form.get("derp_mode", ""), form.get("derp_url", ""))
        except SetupError as exc:
            return self.send(400, derp_page(sess, {"derp_mode": form.get("derp_mode", ""),
                                                   "derp_url": form.get("derp_url", "")}, str(exc)))
        return self.redirect(f"{SETUP}/backups")

    def step_backups(self, method, sess, form, headers):
        data = sess["data"]
        if method == "GET":
            return self.send(200, backups_page(sess, data.get("backups", {})))
        try:
            data["backups"] = check_backups(form.get("backup_schedule", ""), form.get("backup_keep_days", ""),
                                            form.get("backup_enabled", "on") != "off")
        except SetupError as exc:
            return self.send(400, backups_page(sess, dict(form), str(exc)))
        return self.redirect(f"{SETUP}/finish")

    def step_finish(self, method, sess, form, headers):
        wiz, data = self.wizard, sess["data"]
        if method == "GET":
            return self.send(200, finish_page(sess, data))
        if not wiz.finish_lock.acquire(blocking=False):
            return self.send(409, finish_page(sess, data, _("Setup is already running. Wait a moment.")))
        try:
            # two-factor is optional here: the console recommends it after the first sign-in
            stored = {"ui_lang": data["lang"], "mfa_required": "optional", **data["server"], **data["network"], **data["derp"], **data["backups"],
                      "signup_mode": data["signup"]["signup_mode"],
                      "admin_email": data["admin"]["email"]}
            try:
                wiz.finisher.run({k: v for k, v in stored.items() if v != ""}, data["admin"]["username"])
            except SetupError as exc:
                log.error("finish failed: %s", exc)
                return self.send(500, finish_page(sess, data, str(exc)))
            except Exception as exc:  # noqa: BLE001
                log.exception("finish failed")
                return self.send(500, finish_page(sess, data, _("Unexpected error: {detail}", detail=str(exc))))
            wiz.finished = True
            first_key = ""
            if data["signup"].get("first_key"):
                try:  # shown on the next page only; the database keeps just its hash
                    first_key = lac.create_signup_key(_("First key"), 1, 168)
                except Exception:  # noqa: BLE001 - setup is done; the admin can create keys in the console
                    log.exception("could not create the first sign-up key")
            page = done_page(data["server"]["public_url"], first_key)
            threading.Timer(EXIT_DELAY, wiz.exit_callback).start()
            return self.send(200, page)
        finally:
            wiz.finish_lock.release()


def create_admin(email: str, username: str, password: str) -> int:
    """Create the admin account, or reuse the one a previous attempt left (same email)."""
    existing = lac.get_account(email=email)
    if existing:
        lac.update_password(existing["id"], password)
        lac.set_account_role(existing["id"], "admin")
        return existing["id"]
    try:
        return lac.create_account(username=username, email=email, password=password, role="admin",
                                  headscale_user=username)
    except ValueError as exc:
        raise SetupError(str(exc)) from exc


def make_server(wizard: Wizard, host=HOST, port=PORT) -> ThreadingHTTPServer:
    handler = type("WizardHandler", (Handler,), {"wizard": wizard})
    server = ThreadingHTTPServer((host, port), handler)
    return server


def main() -> int:
    logging.basicConfig(level=logging.INFO, stream=sys.stdout, format="%(message)s")
    data_dir = os.environ.get("HSE_DATA_DIR", render.DATA_DIR)
    lac.configure(os.path.join(data_dir, "console", "accounts.db"))
    token = ensure_token(data_dir)
    print(banner(token), flush=True)

    wizard = Wizard(data_dir)
    server = make_server(wizard)
    wizard.exit_callback = lambda: threading.Thread(target=server.shutdown, daemon=True).start()
    signal.signal(signal.SIGTERM, lambda *_a: threading.Thread(target=server.shutdown, daemon=True).start())
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    server.server_close()
    return 0 if wizard.finished else 1


if __name__ == "__main__":
    sys.exit(main())
