"""The contract the console relies on from Headscale (its REST API and the all-in-one supervisor).

``headscale`` is the one implementation. The Protocol exists so that the contract is written down once, tests
can build fakes that reject calls outside it (``mock.create_autospec``) and a test can check that the real
module still honours it. Nothing is injected at run time: there is a single implementation, so the handlers
keep calling the module directly.
"""

from __future__ import annotations

from typing import Protocol


class HeadscaleClient(Protocol):
    # --- nodes (machines) ---
    def all_nodes(self) -> list[dict]: ...
    def get_node(self, node_id: str) -> dict | None: ...
    def owned_node(self, user: dict | None, node_id: str) -> dict | None: ...
    def user_nodes(self, user: dict) -> list[dict]: ...
    def host_details(self, node_ids: list[str]) -> dict[str, dict]: ...
    def latest_tailscale_version(self) -> str: ...

    # --- users ---
    def all_users(self) -> list[dict]: ...
    def user_by_name(self, username: str) -> dict | None: ...
    def user_for_sub(self, sub: str) -> dict | None: ...
    def create_user(self, username: str) -> dict: ...

    # --- keys ---
    def all_keys(self) -> list[dict]: ...
    def user_keys(self, user: dict) -> list[dict]: ...
    def owned_key(self, user: dict | None, key_id: str) -> dict | None: ...
    def api_keys(self) -> list[dict]: ...
    def own_api_key_prefix(self) -> str: ...
    def api_key_prefix(self, key: str) -> str: ...

    # --- policy, DNS, DERP, key expiry (config.yaml settings go through the supervisor) ---
    def get_policy(self) -> dict: ...
    def dns_config(self) -> dict: ...
    def derp_regions(self) -> dict[int, str]: ...
    def key_expiry_days(self) -> int | None: ...
    def apply_dns(self, cfg: dict) -> tuple[bool, str]: ...
    def apply_key_expiry(self, days: int) -> tuple[bool, str]: ...

    # --- supervisor ---
    def control_available(self) -> bool: ...
    def control_status(self) -> dict | None: ...
    def control_backup(self) -> str: ...
    def control_backup_settings(self, enabled: bool, schedule: str, keep_days: str) -> tuple[str, str]: ...
    def control_backup_upload(self, tmp: str, name: str) -> tuple[str, str]: ...
    def control_restore(self, name: str) -> tuple[str, str]: ...
    def restore_result(self) -> dict | None: ...

    # --- errors ---
    def api_error(self, exc: Exception) -> str: ...

    # --- raw access: still used directly by the handlers; the named operations above are meant to replace it ---
    def api(self, method: str, path: str, body: dict | None = None) -> dict: ...
